name: Exemplo de Workflow Encadeado

on: push

jobs:

  job_A:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Executar a tarefa A
      run: echo "Executando a tarefa A"

  job_B:
    needs: job_A
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Executar a tarefa B
      run: echo "Executando a tarefa B ap처s a conclus찾o da tarefa A"

  job_C:
    needs: job_B
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Executar a tarefa C
      run: echo "Executando a tarefa C ap처s a conclus찾o da tarefa B"
