name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'CHANGELOG.md'
          version-file: 'package.json'

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Bump version to ${{ steps.changelog.outputs.new-version }}"
          add: 'package.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}