name: Novo Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configuração do ambiente
        run: echo "A nova release foi criada e o workflow foi disparado com sucesso!"

      - name: Outros passos
        run: |
          echo "Aqui você pode adicionar outros comandos para serem executados."
