name: Trigger on Success

on:
  workflow_run:
    workflows: ["Create Tag"]
    types:
      - completed
  push:
    branches:
      - development

jobs:
  deploy-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger - Deploy Prod
        run: echo "O workflow Create Tag foi executado com sucesso!"

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger - Push Development
        run: echo "Houve um push na branch development!"