name: Trigger on Success

on:
  workflow_run:
    workflows: ["Create Tag"]
    types:
      - completed
  push:
    branches:
      - development

jobs:
  trigger-on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger on Success
        run: echo "O workflow Create Tag foi executado com sucesso!"

  trigger-on-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger on Push to Development
        run: echo "Houve um push na branch development!"