name: Release and Deploy

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy-to-production:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger - Initing deploy
        run: echo "Iniciando release e deploy..."
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.github_token }}
          
      - name: Print release tag
        run: echo "The release tag is ${{ github.event.release.tag_name }}"
              
      # - name: create release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.github_token }}
      #   with:
          
      #     tag_name: ${{ steps.changelog.outputs.tag }}
      #     release_name: ${{ steps.changelog.outputs.tag }}
      #     body: ${{ steps.changelog.outputs.clean_changelog }}
      
      - name: Trigger - Deploy Prod
        run: echo "Release e deploy sucesso!"

  deploy-to-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger - Push Development
        run: echo "Houve um push na branch development!"